### ISSUE TITLE
urllib.error.URLError: <urlopen error unknown url type: e>

### ISSUE THREAD

**Issue by judian17** [smthemex/ComfyUI_TRELLIS#2]
实测在秋叶包可以运行，但dino模型放在comfyUI/models/dinov2目录下识别不到，显示如题错误。放在"comfyui的.cache\torch\hub\checkpoints\dinov2_vitl14_reg4_pretrain.pth"时可以运行。

**Comment by judian17** [comment]
补充说明：dino模型放在comfyUI/models/dinov2目录下可以识别到，能在节点内选中，但无法加载。需要在comfyui\.cache\torch\hub\checkpoints\路径下也存在一个模型。即两个文件夹内均要有一个模型

**Comment by smthemex** [comment]
had fix it
