### ISSUE TITLE
GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'

### ISSUE THREAD

**Issue by 111496583yzy** [smthemex/ComfyUI_TRELLIS#8]
got prompt
[SPARSE][CONV] spconv algo: auto
[ATTENTION] Using backend: flash_attn
using MLP layer as FFN

Sampling: 100%|██████████| 12/12 [00:01<00:00, 10.35it/s]

Sampling: 100%|██████████| 12/12 [00:03<00:00,  3.03it/s]
Before postprocess: 612412 vertices, 1225374 faces

Decimating Mesh: 100%|██████████[00:06<00:00]
After decimate: 30300 vertices, 61268 faces

Rasterizing: 100%|██████████| 1000/1000 [00:00<00:00, 1299.53it/s]
Found 122 invisible faces
Dual graph: 91690 edges
Mincut solved, start checking the cut
Removed 716 faces by mincut
WARNING- Some cuts were necessary to cope with non manifold configuration.
INFO- Loaded 29950 vertices and 60552 faces.

100% done After remove invisible faces: 30076 vertices, 60616 faces

Rendering: 0it [00:00, ?it/s]
Rendering: 0it [00:00, ?it/s]
!!! Exception during processing !!! GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'
Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/execution.py", line 348, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 218, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 189, in _map_node_over_list
process_inputs(input_dict, i)
File "/root/autodl-tmp/ComfyUI/execution.py", line 178, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/TRELLIS_node.py", line 107, in sampler_main
glb=image_to_3d(model,img,preprocess_image,covert2video,trial_id,seed,cfg,steps,slat_cfg,slat_steps,mesh_simplify,texture_size,mode)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/app.py", line 48, in image_to_3d
glb = postprocessing_utils.to_glb(
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/utils/postprocessing_utils.py", line 455, in to_glb
observations, extrinsics, intrinsics = render_multiview(app_rep, resolution=texture_size, nviews=100)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/utils/render_utils.py", line 110, in render_multiview
res = render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/utils/render_utils.py", line 76, in render_frames
res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/renderers/gaussian_render.py", line 222, in render
render_ret = render_(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_TRELLIS/trellis/renderers/gaussian_render.py", line 72, in render_
raster_settings = GaussianRasterizationSettings(
TypeError: GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'

Prompt executed in 67.95 seconds

**Comment by smthemex** [comment]
try reinstall diff-gaussian-rasterization，
git clone https://github.com/autonomousvision/mip-splatting.git ./tmp/extensions/mip-splatting
pip install ./tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/

**Comment by 111496583yzy** [comment]
> 尝试重新安装 diff-gaussian-rasterization，git 克隆https://github.com/autonomousvision/mip-splatting.git ./tmp/extensions/mip-splatting pip install ./tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/

"Is there a specific version requirement?"

** Python version: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]
Total VRAM 24210 MB, total RAM 1031718 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 D : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /root/autodl-tmp/ComfyUI/web
Total VRAM 24210 MB, total RAM 1031718 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 D : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V7.14)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.

**Comment by smthemex** [comment]
确认去除白底后的图片是否正常，有些脱底节点输出的图片格式不对

**Comment by 111496583yzy** [comment]
> 确认去除白底后的图片是否正常，有些脱底节点输出的图片格式不对

有推荐的抠图节点吗？抠完图保存在上传回去就正常了

**Comment by smthemex** [comment]
你开启preprocesse image 会自动处理的
